/* eslint-disable @next/next/no-img-element */
import React, { useState } from "react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";

export default function Header() {
  const router = useRouter();
  const page = router && router.pathname ? router.pathname.substring(1) : "";
  const [dropDown0, setDropDown0] = useState(false);
  const [dropDown, setDropDown] = useState(false);

  return (
    <>
      <Head>
        <title>POYA</title>
        <meta name="description" content="Generated by R.A.H" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/titleLogo.svg" />
      </Head>
      <div className="header-main">
        <div
          className="container-fluid position-relative"
          style={{ zIndex: "100", backgroundColor: "#231f1e" }}
        >
          <div className="row">
            <div className="col-2 col-sm-2 col-md-4">
              <div
                className="d-flex align-items-center justify-content-start h-100 position-relative"
                onClick={() => {
                  setDropDown0(!dropDown0);
                  setDropDown(false);
                }}
              >
                <div>
                  <img
                    src="/assets/Untitled-2-03.svg"
                    width="20px"
                    alt="menu"
                    style={{
                      transform: dropDown0
                        ? "rotateX(180deg)"
                        : "rotateY(0deg)",
                      transition: "all 0.3s",
                      cursor: "pointer",
                    }}
                  />
                </div>
              </div>
            </div>
            <div className="col-8 col-sm-8 col-md-4 text-center my-4">
              <img
                src="/assets/Untitled-2-04.svg"
                width="30%"
                alt="hess"
                className=""
              />
              {/* <div className="header-top-text1">حس یک نگاه</div>
              <div className="header-top-text2">
                خلق آنچه تا ابد خلق می کند.
              </div> */}
            </div>
            <div className="col-2 col-sm-2 col-md-4">
              <div className="d-flex align-items-center justify-content-end h-100">
                {/* <div className="dirltr footer-tel ms-3 d-none d-sm-none d-md-none d-lg-block">
                  021 - 22 72 40 59
                </div> */}
                <img
                  src="/assets/Untitled-2-02.svg"
                  width="17px"
                  alt="tell"
                  // style={{
                  //   filter:
                  //     "invert(48%) sepia(75%) saturate(856%) hue-rotate(349deg) brightness(106%) contrast(95%)",
                  // }}
                />
              </div>
            </div>
          </div>
        </div>
        <div className="header-menu-main-container"></div>
        <div className="container-fluid p-0">
          <div className="row m-0">
            <div className="col-12 p-0" style={{ height: "0px" }}>
              {/* MOBILE MENU */}
              {/* <div
                className="position-absolute header-menu-item-drop-mobile d-lg-none"
                style={{ display: dropDown0 ? "block" : "none" }}
              >
                <div className=" py-2 px-2 header-menu-item-drop-child-other">
                  برندینگ فضا
                </div>
                <div className=" py-2 px-2 header-menu-item-drop-child-other">
                  مشاوره
                </div>
                <div className=" py-2 px-2 header-menu-item-drop-child-other">
                  dycada
                </div>
                <div className=" py-2 ps-3 pe-2 header-menu-item-drop-child-other">
                  درباره حس یک نگاه
                </div>
              </div> */}
              {/* DESKTOP MENU */}
              <div
                className="header-menu-main justify-content-between d-block d-sm-block d-md-block d-lg-flex"
                style={{ top: dropDown0 ? "0px" : "-190px" }}
              >
                <div
                  className="header-menu-item-drop-parent position-relative py-2 pe-4 ps-2"
                  onClick={() => setDropDown(!dropDown)}
                  style={{ backgroundColor: dropDown ? "#f8821e" : "inherit" }}
                >
                  خدمات برندینگ در صنعت ساختمان، معماری و شهرسازی{" "}
                  <img
                    src="/assets/Untitled-2-03.svg"
                    width="13px"
                    alt=""
                    className="header-drop-arrow-desktop mb-1 me-2"
                    style={{
                      transform: dropDown ? "rotateX(180deg)" : "rotateY(0deg)",
                    }}
                  />
                  <div
                    className="header-menu-item-drop-child position-absolute px-2"
                    style={{ display: dropDown ? "block" : "none" }}
                  >
                    <div className="mt-2 mb-3 header-menu-item-drop-child-option">
                      برندینگ برای معماران
                    </div>
                    <div className="mb-3 header-menu-item-drop-child-option">
                      برندینگ برای سازندگان
                    </div>
                    <div className="mb-3 header-menu-item-drop-child-option">
                      برندینگ برای تامین کنندگان
                    </div>
                    <div className="mb-3 header-menu-item-drop-child-option">
                      برندینگ ساختمان
                    </div>
                    <div className="mb-3 header-menu-item-drop-child-option">
                      برندینگ شهری
                    </div>
                  </div>
                </div>
                <div className=" py-2 px-4 px-lg-2 header-menu-item-drop-child-other">
                  برندینگ فضا
                </div>
                <div className=" py-2 px-4 px-lg-2 header-menu-item-drop-child-other">
                  مشاوره
                </div>
                <div className=" py-2 px-4 px-lg-2 header-menu-item-drop-child-other">
                  dycada
                </div>
                <div className=" py-2 ps-3 pe-4 pe-lg-2 header-menu-item-drop-child-other">
                  درباره حس یک نگاه
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
